name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./prototype_1_pong # temp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@ac5bf11548bf5e19b8aadb8182072616590fa4a6
        with:
          package_json_file: "prototype_1_pong/package.json"
      - uses: actions/setup-node@v7
        with:
          node-version-file: "prototype_1_pong/.node-version"
      - name: Download Usagi and build
        shell: bash
        run: |
          set -e pipefail
          USAGI_VERSION="$(cat .usagi-version)"
          url="https://github.com/brettchalupa/usagi/releases/download/v$USAGI_VERSION/usagi-$USAGI_VERSION-linux-x86_64.tar.gz"
          curl --fail --location --silent --show-error "$url" -o usagi.tar.gz
          mkdir -p bin
          tar -xzf "usagi.tar.gz" -O ./usagi > bin/usagi
          chmod +x ./bin/usagi
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Unzip build
        run: |
          cd export
          unzip -q web.zip -d _site
      - uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./prototype_1_pong/export/_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
